version: '3.9'

services:
  react:
    build: ./frontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - mern-app
  api:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  